import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { MessageCircle, X, Send, Bot, User, Sparkles, Loader2, Trash2, ChevronDown, Mic, MicOff, Volume2 } from 'lucide-react';

const AIChatbot = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([
    { 
      id: 1, 
      type: 'bot', 
      text: 'Hi! I\'m your Civic Reporter AI assistant. I can help you with:\n\n• Reporting issues\n• Tracking complaints\n• Understanding the process\n• Finding nearby authorities\n\nWhat can I help you with today?',
      timestamp: new Date()
    }
  ]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isListening, setIsListening] = useState(false);
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);
  const recognitionRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isOpen]);

  useEffect(() => {
    if (isOpen && inputRef.current) {
      inputRef.current.focus();
    }
  }, [isOpen]);

  // Initialize Speech Recognition
  useEffect(() => {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (SpeechRecognition) {
      const recognition = new SpeechRecognition();
      recognition.continuous = false;
      recognition.interimResults = true;
      recognition.lang = 'en-IN'; // Support Indian English

      recognition.onresult = (event) => {
        let transcript = '';
        for (let i = event.resultIndex; i < event.results.length; i++) {
          transcript += event.results[i][0].transcript;
        }
        setInput(transcript);
        
        // If final result, auto-send
        if (event.results[event.results.length - 1].isFinal) {
          setIsListening(false);
        }
      };

      recognition.onerror = (event) => {
        console.error('Speech recognition error:', event.error);
        setIsListening(false);
      };

      recognition.onend = () => {
        setIsListening(false);
      };

      recognitionRef.current = recognition;
    }

    return () => {
      if (recognitionRef.current) {
        try { recognitionRef.current.stop(); } catch {}
      }
    };
  }, []);

  const toggleVoice = () => {
    if (!recognitionRef.current) {
      // Fallback alert if speech recognition not supported
      alert('Voice recognition is not supported in this browser. Please use Chrome or Edge.');
      return;
    }

    if (isListening) {
      recognitionRef.current.stop();
      setIsListening(false);
    } else {
      setInput('');
      recognitionRef.current.start();
      setIsListening(true);
    }
  };

  const handleSend = async () => {
    if (!input.trim()) return;

    const userMessage = {
      id: Date.now(),
      type: 'user',
      text: input,
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);
    const query = input.toLowerCase();
    setInput('');
    setIsTyping(true);

    // Smart response generation based on keywords
    setTimeout(() => {
      let responseText = '';

      if (query.includes('report') || query.includes('submit') || query.includes('complaint')) {
        responseText = "📝 To report an issue:\n\n1. Go to the **Submit** page\n2. Upload a photo of the problem\n3. Our AI will automatically detect the issue type\n4. Verify the details and submit\n\nYour complaint will be sent to the appropriate authority!";
      } else if (query.includes('track') || query.includes('status') || query.includes('my complaint')) {
        responseText = "📊 To track your complaints:\n\n1. Visit **My Complaints** from the menu\n2. You'll see all your submitted complaints with their current status\n3. Each complaint has a unique ID you can use to search\n\nStatus updates: Pending → In Progress → Resolved";
      } else if (query.includes('pdf') || query.includes('download') || query.includes('letter')) {
        responseText = "📄 You can download a formal complaint letter in PDF format after submitting your complaint. The letter is auto-generated by AI and addressed to the correct local authority.";
      } else if (query.includes('location') || query.includes('gps') || query.includes('where')) {
        responseText = "📍 The app automatically detects your location using GPS and identifies the correct authority (Gram Panchayat, Municipal Council, or Corporation). You can also drag the map pin to adjust the exact location.";
      } else if (query.includes('admin') || query.includes('authority')) {
        responseText = "🏛️ The system auto-detects the right authority based on your location:\n\n• 🏘️ Village → Gram Panchayat (Sarpanch)\n• 🏛️ Town → Municipal Council (Chief Officer)\n• 🏙️ City → Municipal Corporation (Commissioner)";
      } else if (query.includes('urgent') || query.includes('emergency') || query.includes('high priority')) {
        responseText = "🚨 For urgent issues:\n\n1. Set severity to **High** when submitting\n2. High severity complaints are prioritized by the admin\n3. Consider also contacting local emergency services (100/112) for immediate danger";
      } else if (query.includes('spam') || query.includes('fake') || query.includes('reputation')) {
        responseText = "🛡️ We have a multi-layer anti-spam system:\n\n• AI validates your image (rejects selfies, food, etc.)\n• Rate limit: Max 5 complaints/day\n• Reputation system: Valid complaints earn points, fake ones lose points\n• Admin moderation for flagged complaints";
      } else if (query.includes('translate') || query.includes('language') || query.includes('hindi')) {
        responseText = "🌐 We support 13 Indian languages! After the AI generates your complaint letter in English, you can translate it to Hindi, Marathi, Tamil, Telugu, and more using the language selector.";
      } else if (query.includes('hello') || query.includes('hi') || query.includes('hey')) {
        responseText = "👋 Hello! I'm your Civic Reporter AI assistant. How can I help you today? You can ask me about reporting issues, tracking complaints, or understanding how the system works!";
      } else if (query.includes('thank') || query.includes('thanks')) {
        responseText = "😊 You're welcome! Happy to help. If you have any other questions, feel free to ask anytime!";
      } else {
        responseText = "I can help you with:\n\n• 📝 **Reporting issues** — how to submit complaints\n• 📊 **Tracking status** — check your complaint progress\n• 📍 **Location** — how GPS detection works\n• 🏛️ **Authorities** — who handles your complaint\n• 🛡️ **Anti-spam** — our verification system\n• 🌐 **Translation** — available languages\n\nTry asking about any of these topics!";
      }
      
      const botResponse = {
        id: Date.now() + 1,
        type: 'bot',
        text: responseText,
        timestamp: new Date()
      };
      
      setMessages(prev => [...prev, botResponse]);
      setIsTyping(false);
    }, 800 + Math.random() * 700);
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const clearChat = () => {
    setMessages([{
      id: Date.now(),
      type: 'bot',
      text: 'Chat cleared! How can I help you today?',
      timestamp: new Date()
    }]);
  };

  return (
    <>
      {/* Floating Toggle Button — RIGHT CORNER */}
      <AnimatePresence>
        {!isOpen && (
          <motion.button
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0, opacity: 0 }}
            transition={{ type: 'spring', stiffness: 300, damping: 20 }}
            onClick={() => setIsOpen(true)}
            className="fixed bottom-8 right-8 z-40 group"
            whileHover={{ scale: 1.1 }}
            whileTap={{ scale: 0.9 }}
          >
            {/* Button with AI Avatar */}
            <div className="relative w-16 h-16 bg-[#0B0F19] rounded-full shadow-xl shadow-blue-500/30 flex items-center justify-center overflow-hidden border border-blue-500/30">
              {/* Floating animation wrapper */}
              <motion.div
                animate={{ 
                  y: [0, -8, 0],
                  rotate: [0, 3, -3, 0]
                }}
                transition={{ 
                  duration: 3, 
                  repeat: Infinity, 
                  ease: "easeInOut" 
                }}
                className="relative w-full h-full flex items-center justify-center"
              >
                <img 
                  src="/AI-Face.png" 
                  alt="AI Assistant" 
                  className="w-14 h-14 object-cover rounded-full bg-transparent" 
                  style={{ 
                    mixBlendMode: 'screen',
                    filter: 'drop-shadow(0 0 10px rgba(59, 130, 246, 0.5))'
                  }}
                  onError={(e) => {e.target.style.display='none'; e.target.nextSibling.style.display='block'}} 
                />
                <MessageCircle className="w-7 h-7 text-white hidden" />
              </motion.div>
              
            </div>
            
            {/* Pulse ring */}
            <motion.div
              className="absolute inset-0 rounded-full border-2 border-blue-400/30"
              animate={{ scale: [1, 1.3, 1.5], opacity: [0.4, 0.1, 0] }}
              transition={{ duration: 2, repeat: Infinity }}
            />
          </motion.button>
        )}
      </AnimatePresence>

      {/* Chat Window — RIGHT CORNER */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            transition={{ type: 'spring', stiffness: 300, damping: 25 }}
            className="fixed bottom-8 right-8 w-[380px] h-[550px] z-50"
          >
            <div className="relative w-full h-full glass-premium rounded-3xl border border-white/10 shadow-2xl overflow-hidden flex flex-col">
              {/* Background glow */}
              <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/10 rounded-full blur-[100px] pointer-events-none" />
              <div className="absolute bottom-0 left-0 w-48 h-48 bg-purple-500/10 rounded-full blur-[80px] pointer-events-none" />
              
              {/* Header */}
              <div className="relative flex items-center justify-between px-5 py-4 bg-gradient-to-r from-blue-500/20 to-purple-500/20 border-b border-white/10">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-transparent flex items-center justify-center shadow-lg overflow-hidden">
                    <motion.div
                      animate={{ 
                        y: [0, -4, 0],
                        rotate: [0, 2, -2, 0]
                      }}
                      transition={{ 
                        duration: 2.5, 
                        repeat: Infinity, 
                        ease: "easeInOut" 
                      }}
                      className="w-full h-full flex items-center justify-center"
                    >
                      <img 
                        src="/AI-Face.png" 
                        alt="AI Assistant" 
                        className="w-10 h-10 object-cover rounded-full"
                        style={{ 
                          mixBlendMode: 'screen',
                          filter: 'drop-shadow(0 0 8px rgba(59, 130, 246, 0.4))'
                        }}
                        onError={(e) => {e.target.style.display='none'; e.target.nextSibling.style.display='flex'}} 
                      />
                    </motion.div>
                    <Bot className="w-5 h-5 text-white hidden" />
                  </div>
                  <div>
                    <h3 className="font-bold text-white text-sm">Civic AI</h3>
                    <div className="flex items-center gap-1.5">
                      <motion.div
                        className="w-2 h-2 bg-green-400 rounded-full"
                        animate={{ scale: [1, 1.2, 1] }}
                        transition={{ duration: 2, repeat: Infinity }}
                      />
                      <span className="text-xs text-gray-400">Online • Voice Enabled</span>
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center gap-1">
                  <motion.button
                    onClick={clearChat}
                    className="p-2 rounded-lg hover:bg-white/10 transition-colors text-gray-400 hover:text-white"
                    whileHover={{ scale: 1.1 }}
                    whileTap={{ scale: 0.9 }}
                    title="Clear chat"
                  >
                    <Trash2 className="w-4 h-4" />
                  </motion.button>
                  <motion.button
                    onClick={() => setIsOpen(false)}
                    className="p-2 rounded-lg hover:bg-white/10 transition-colors text-gray-400 hover:text-white"
                    whileHover={{ scale: 1.1 }}
                    whileTap={{ scale: 0.9 }}
                  >
                    <X className="w-5 h-5" />
                  </motion.button>
                </div>
              </div>

              {/* Messages */}
              <div className="flex-1 overflow-y-auto p-4 space-y-4 scrollbar-thin scrollbar-thumb-white/10 scrollbar-track-transparent">
                {messages.map((msg) => (
                  <motion.div
                    key={msg.id}
                    initial={{ opacity: 0, y: 10, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    transition={{ type: 'spring', stiffness: 300, damping: 25 }}
                    className={`flex ${msg.type === 'user' ? 'justify-end' : 'justify-start'}`}
                  >
                    <div className={`flex gap-2 max-w-[85%] ${msg.type === 'user' ? 'flex-row-reverse' : ''}`}>
                      {/* Avatar */}
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 overflow-hidden ${
                        msg.type === 'user' 
                          ? 'bg-purple-500/20' 
                          : 'bg-transparent'
                      }`}>
                        {msg.type === 'user' ? (
                          <User className="w-4 h-4 text-purple-400" />
                        ) : (
                          <>
                            <img 
                              src="/AI-Face.png" 
                              alt="AI" 
                              className="w-8 h-8 object-cover rounded-full"
                              style={{ 
                                mixBlendMode: 'screen',
                                filter: 'drop-shadow(0 0 6px rgba(59, 130, 246, 0.3))'
                              }}
                              onError={(e) => {e.target.style.display='none'; e.target.nextSibling.style.display='flex'}} 
                            />
                            <Sparkles className="w-4 h-4 text-white hidden" />
                          </>
                        )}
                      </div>
                      
                      {/* Message bubble */}
                      <div className={`px-4 py-3 rounded-2xl text-sm leading-relaxed whitespace-pre-wrap ${
                        msg.type === 'user'
                          ? 'bg-purple-500/20 text-white rounded-br-md border border-purple-500/20'
                          : 'bg-white/5 text-gray-200 rounded-bl-md border border-white/10'
                      }`}>
                        {msg.text}
                      </div>
                    </div>
                  </motion.div>
                ))}
                
                {/* Typing indicator */}
                {isTyping && (
                  <motion.div
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="flex justify-start"
                  >
                    <div className="flex gap-2">
                      <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center">
                        <Sparkles className="w-4 h-4 text-white" />
                      </div>
                      <div className="px-4 py-3 rounded-2xl bg-white/5 border border-white/10 rounded-bl-md">
                        <div className="flex gap-1">
                          {[0, 1, 2].map((i) => (
                            <motion.div
                              key={i}
                              className="w-2 h-2 bg-blue-400 rounded-full"
                              animate={{ y: [0, -6, 0] }}
                              transition={{ duration: 0.6, repeat: Infinity, delay: i * 0.1 }}
                            />
                          ))}
                        </div>
                      </div>
                    </div>
                  </motion.div>
                )}
                <div ref={messagesEndRef} />
              </div>

              {/* Input with Voice */}
              <div className="relative p-4 border-t border-white/10 bg-black/20">
                {/* Voice Recording Indicator */}
                <AnimatePresence>
                  {isListening && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      className="mb-3 flex items-center gap-3 px-4 py-2.5 rounded-xl bg-red-500/10 border border-red-500/30"
                    >
                      <motion.div
                        className="w-3 h-3 bg-red-500 rounded-full"
                        animate={{ scale: [1, 1.3, 1], opacity: [1, 0.5, 1] }}
                        transition={{ duration: 0.8, repeat: Infinity }}
                      />
                      <span className="text-xs text-red-400 font-medium">Listening... speak now</span>
                      {/* Mini waveform */}
                      <div className="flex items-center gap-0.5 ml-auto">
                        {[0,1,2,3,4,5,6].map(i => (
                          <motion.div
                            key={i}
                            className="w-1 bg-red-400 rounded-full"
                            animate={{ height: [4, 12 + Math.random() * 8, 4] }}
                            transition={{ duration: 0.4, repeat: Infinity, delay: i * 0.05 }}
                          />
                        ))}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                <div className="flex gap-2">
                  {/* Voice Button */}
                  <motion.button
                    onClick={toggleVoice}
                    className={`px-3 py-3 rounded-xl font-medium text-sm flex items-center justify-center transition-all ${
                      isListening
                        ? 'bg-red-500/20 text-red-400 border border-red-500/30 shadow-lg shadow-red-500/20'
                        : 'bg-white/5 border border-white/10 text-gray-400 hover:text-blue-400 hover:border-blue-500/30 hover:bg-blue-500/10'
                    }`}
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    title={isListening ? "Stop listening" : "Voice search"}
                  >
                    {isListening ? (
                      <motion.div animate={{ scale: [1, 1.2, 1] }} transition={{ duration: 0.5, repeat: Infinity }}>
                        <MicOff className="w-5 h-5" />
                      </motion.div>
                    ) : (
                      <Mic className="w-5 h-5" />
                    )}
                  </motion.button>

                  <div className="flex-1 relative">
                    <input
                      ref={inputRef}
                      type="text"
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      onKeyPress={handleKeyPress}
                      placeholder={isListening ? "🎤 Listening..." : "Ask me anything..."}
                      className={`w-full bg-white/5 border rounded-xl px-4 py-3 pr-12 text-sm text-white placeholder-gray-500 focus:outline-none focus:ring-2 transition-all ${
                        isListening 
                          ? 'border-red-500/30 focus:ring-red-500/50' 
                          : 'border-white/10 focus:ring-blue-500/50 focus:border-blue-500/30'
                      }`}
                    />
                    <div className="absolute right-3 top-1/2 -translate-y-1/2">
                      <Sparkles className="w-4 h-4 text-blue-400/50" />
                    </div>
                  </div>
                  <motion.button
                    onClick={handleSend}
                    disabled={!input.trim() || isTyping}
                    className={`px-4 py-3 rounded-xl font-medium text-sm flex items-center justify-center transition-all ${
                      input.trim() && !isTyping
                        ? 'bg-gradient-to-r from-blue-500 to-purple-600 text-white shadow-lg shadow-blue-500/25'
                        : 'bg-white/5 text-gray-500 cursor-not-allowed'
                    }`}
                    whileHover={input.trim() && !isTyping ? { scale: 1.05 } : {}}
                    whileTap={input.trim() && !isTyping ? { scale: 0.95 } : {}}
                  >
                    {isTyping ? (
                      <Loader2 className="w-5 h-5 animate-spin" />
                    ) : (
                      <Send className="w-5 h-5" />
                    )}
                  </motion.button>
                </div>
                
                {/* Quick suggestions */}
                <div className="flex gap-2 mt-3 overflow-x-auto scrollbar-thin pb-1">
                  {['How to report?', 'Track complaint', 'Anti-spam system', 'Translate letter'].map((suggestion) => (
                    <motion.button
                      key={suggestion}
                      onClick={() => setInput(suggestion)}
                      className="flex-shrink-0 px-3 py-1.5 rounded-full bg-white/5 border border-white/10 text-xs text-gray-400 hover:text-white hover:bg-white/10 hover:border-white/20 transition-all whitespace-nowrap"
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                    >
                      {suggestion}
                    </motion.button>
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
};

export default AIChatbot;
